[package]
description = "hbbft consensus protocol Engine"
name = "hbbft_engine"
version = "0.0.1"
license = "GPL-3.0"
authors = [
    "Andreas Fackler <AndreasFackler@gmx.de>",
    "David Forstenlechner <dforsten@gmail.com>"
]

[lib]

[dependencies]
rustc-hex = "1.0"
serde_json = "1.0"
parking_lot = "0.6"
inventory = "0.1"

keccak-hash = "0.1"
ethcore = { path = ".." }
ethereum-types = "0.4"
ethcore-miner = { path = "../../miner" }
hbbft = { git = "https://github.com/poanetwork/hbbft" }
ethkey = { path = "../../accounts/ethkey" }

common-types = { path = "../types" }

[dev-dependencies]
ethcore = { path = "..", features = ["test-helpers"] }
ethcore-accounts = { path = "../../accounts" }
rand = "0.6.1"

[features]
# Include tools to facilitate test setup.
test-helpers = ["ethcore/test-helpers"]
